from __future__ import annotations

from enum import StrEnum


class ReviewStatus(StrEnum):
    FINAL_AUTHORIZED = "FINAL_AUTHORIZED"
    DRAFT_FOR_CLINICIAN_REVIEW = "DRAFT_FOR_CLINICIAN_REVIEW"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    CONFLICT_REQUIRES_REVIEW = "CONFLICT_REQUIRES_REVIEW"
    URGENT_CLINICAL_REVIEW = "URGENT_CLINICAL_REVIEW"
    EMERGENCY_ESCALATION = "EMERGENCY_ESCALATION"
    SYSTEM_UNAVAILABLE = "SYSTEM_UNAVAILABLE"


class EvidenceGrade(StrEnum):
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"


class RecommendationAction(StrEnum):
    CONTINUE = "CONTINUE"
    START = "START"
    ADJUST = "ADJUST"
    HOLD = "HOLD"
    STOP = "STOP"
    NO_CHANGE = "NO_CHANGE"
    NO_RECOMMENDATION = "NO_RECOMMENDATION"


class ClaimType(StrEnum):
    PATIENT_FACT = "PATIENT_FACT"
    AUTHORIZED_ORDER = "AUTHORIZED_ORDER"
    POLICY_REQUIREMENT = "POLICY_REQUIREMENT"
    EXTERNAL_EVIDENCE = "EXTERNAL_EVIDENCE"
    MODEL_INTERPRETATION = "MODEL_INTERPRETATION"


class AuthorizationStatus(StrEnum):
    SIGNED = "SIGNED"
    PENDING = "PENDING"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"
    SUPERSEDED = "SUPERSEDED"
    UNAVAILABLE = "UNAVAILABLE"


class CorpusEligibility(StrEnum):
    RUNTIME = "runtime"
    GOVERNANCE = "governance"
    EVALUATION = "evaluation"


class Severity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    URGENT = "URGENT"
    EMERGENCY = "EMERGENCY"
    CRITICAL = "CRITICAL"
